version: "3"

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8082"
    ports:
      - "8082:8082"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - app-tier

  ports:
    build:
      context: .
    ports:
      - "8080"
    networks:
      - app-tier
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ports-service.rule=PathPrefix(`/v1/ports`)"
    deploy:
      resources:
        limits:
          memory: 200M

networks:
  app-tier:
    driver: bridge
