version: "3"

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8082"
    ports:
      - "8082:8082"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - app-tier

  ports:
    build:
      context: ./posts
    ports:
      - "8080"
    networks:
      - app-tier
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ports.loadbalancer.server.port=8080"
      - "traefik.http.routers.ports.rule=Host(`ports.localhost`)"
      - "traefik.http.routers.ports.service=ports"
    deploy:
      resources:
        limits:
          memory: 200M

networks:
  app-tier:
    driver: bridge
